env: "local"
http_server:
  timeout: 4s
  idle_timeout: 60s
  cors:
    allowed_origins: [ "https://*", "http://*" ]
    allowed_methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    allowed_headers: [ "Accept", "Authorization", "Content-Type", "X-CSRF-Token" ]
    exposed_headers: [ "Link" ]
    allow_credentials: false
    max_age: 300
    options: false
    debug: false
websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  timeout:
    write: 5s
mqtt:
  host: localhost
  port: 1883
  timeout:
    subscribe: 5s
    publish: 5s
routes:
  /pc:
    topic: "pc"
    required_scope: "mqtt:pc"
    deadline: 1m
  /pc/{id}:
    params: ["id"]
    topic: "pc/{{.id}}"
    required_scope: "mqtt:pc"